tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
tap 'homebrew/python'
tap 'homebrew/versions'

brew 'wget'
brew 'curl'
brew 'openssl'
brew 'git'
#brew 'gnupg'
brew 'gnupg2'
brew 'pinentry-mac'

cask_args appdir: '/Applications'
cask 'Caskroom/cask/atom'
cask 'google-chrome'
#cask 'spotify'
cask 'telegram'
